source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '14.0'

target 'SearchMusic' do
  use_frameworks!

  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxDataSources'
  pod 'Moya/RxSwift'

  pod 'SnapKit'
  
  target 'SearchMusicTests' do
    use_frameworks!
    inherit! :search_paths
    
    pod 'RxBlocking'
    pod 'RxTest'
  end

end
